const BREEDS__LIST = [
  'Select breed',
  'Abyssinian',
  'Aegean',
  'American Shorthair',
  'American Wirehair',
  'Asian',
  'Balinese',
  'Bengal',
  'Birman',
  'British Longhair',
  'British Shorthair',
  'Chartreux',
  'Chausie',
  'Cornish Rex',
  'Devon Rex',
  'Egyptian Mau',
  'German Rex',
  'Himalayan',
  'Javanese',
  'Kanaani',
  'Khao Manee',
  'Korat',
  'LaPerm',
  'Manx',
  'Munchkin',
  'Oriental',
  'Persian',
  'Russian',
  'Scottish Fold',
  'Siberian',
  'Singapura',
  'Sphynx',
  'Ukrainian Levkoy',
  'York Chocolate',
];
export default BREEDS__LIST;
